### ISSUE TITLE
Nombres Poco Intuitivos

### ISSUE THREAD

**Issue by JuanPaMarquez** [SamuelCelisL/GenList#1]
**Muchos de los nombres de las variables son poco intutivos y recomiendo que deben ser cambiados desde ahora que el proyecto no es muy largo**
![Captura de pantalla 2024-04-24 200115](https://github.com/SamuelCelisL/GenList/assets/143953366/a21a3bf1-89a4-4d30-bdc5-3fcec1b5488a)

**Comment by SamuelCelisL** [comment]
ya
